/**
 * BANCO DE PREGUNTAS
 * ------------------
 * Cada pregunta es un objeto con estas propiedades:
 *   - id, categoria, nivel, caracter, pregunta, opciones, respuestaCorrecta
 */

var NihonCheck = window.NihonCheck || {};

NihonCheck.PREGUNTAS = {

  hiragana: [
    {
      id: 'h-001',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'あ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['he', 'wo', 'a', 'jo'],
      respuestaCorrecta: 'a',
    },
    {
      id: 'h-002',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'い',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['me', 'i', 'za', 'da'],
      respuestaCorrecta: 'i',
    },
    {
      id: 'h-003',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'う',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['pi', 'u', 'ne', 'na'],
      respuestaCorrecta: 'u',
    },
    {
      id: 'h-004',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'え',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['myo', 'u', 'myu', 'e'],
      respuestaCorrecta: 'e',
    },
    {
      id: 'h-005',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'お',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ga', 'ja', 'bu', 'o'],
      respuestaCorrecta: 'o',
    },
    {
      id: 'h-006',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'か',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['gya', 'pu', 'mya', 'ka'],
      respuestaCorrecta: 'ka',
    },
    {
      id: 'h-007',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'き',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['cha', 'hi', 're', 'ki'],
      respuestaCorrecta: 'ki',
    },
    {
      id: 'h-008',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'く',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['zo', 'ge', 'ga', 'ku'],
      respuestaCorrecta: 'ku',
    },
    {
      id: 'h-009',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'け',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['o', 'bu', 'ko', 'ke'],
      respuestaCorrecta: 'ke',
    },
    {
      id: 'h-010',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'こ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ko', 'shu', 'u', 'wa'],
      respuestaCorrecta: 'ko',
    },
    {
      id: 'h-011',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'さ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['a', 'sa', 'jo', 'hi'],
      respuestaCorrecta: 'sa',
    },
    {
      id: 'h-012',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'し',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['po', 'ha', 'shi', 'kyo'],
      respuestaCorrecta: 'shi',
    },
    {
      id: 'h-013',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'す',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ke', 'su', 'bi', 're'],
      respuestaCorrecta: 'su',
    },
    {
      id: 'h-014',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'せ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['e', 'ryo', 'se', 'ki'],
      respuestaCorrecta: 'se',
    },
    {
      id: 'h-015',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'そ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['so', 'go', 'su', 'a'],
      respuestaCorrecta: 'so',
    },
    {
      id: 'h-016',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'た',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['byo', 'pya', 'ta', 'so'],
      respuestaCorrecta: 'ta',
    },
    {
      id: 'h-017',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'ち',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['pe', 'so', 'myo', 'chi'],
      respuestaCorrecta: 'chi',
    },
    {
      id: 'h-018',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'つ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['no', 'chu', 'ho', 'tsu'],
      respuestaCorrecta: 'tsu',
    },
    {
      id: 'h-019',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'て',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['te', 'kyo', 'pyo', 'pyu'],
      respuestaCorrecta: 'te',
    },
    {
      id: 'h-020',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'と',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['tsu', 'to', 'bu', 'ze'],
      respuestaCorrecta: 'to',
    },
    {
      id: 'h-021',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'な',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['na', 'ho', 'a', 'gyo'],
      respuestaCorrecta: 'na',
    },
    {
      id: 'h-022',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'に',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ba', 'ni', 'ma', 'me'],
      respuestaCorrecta: 'ni',
    },
    {
      id: 'h-023',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'ぬ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['pa', 'ko', 'nu', 'cho'],
      respuestaCorrecta: 'nu',
    },
    {
      id: 'h-024',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'ね',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ne', 'o', 'n', 'ryu'],
      respuestaCorrecta: 'ne',
    },
    {
      id: 'h-025',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'の',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['yu', 'ku', 'no', 'ri'],
      respuestaCorrecta: 'no',
    },
    {
      id: 'h-026',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'は',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ha', 'pi', 'pu', 'e'],
      respuestaCorrecta: 'ha',
    },
    {
      id: 'h-027',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'ひ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['hi', 'byo', 'hyo', 'zu'],
      respuestaCorrecta: 'hi',
    },
    {
      id: 'h-028',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'ふ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['pyo', 'nyo', 'fu', 'hyo'],
      respuestaCorrecta: 'fu',
    },
    {
      id: 'h-029',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'へ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['mu', 'to', 'bo', 'he'],
      respuestaCorrecta: 'he',
    },
    {
      id: 'h-030',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'ほ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ru', 'ho', 'zu', 'bya'],
      respuestaCorrecta: 'ho',
    },
    {
      id: 'h-031',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'ま',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['bu', 'ma', 'ne', 'cha'],
      respuestaCorrecta: 'ma',
    },
    {
      id: 'h-032',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'み',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['sha', 'cho', 'jo', 'mi'],
      respuestaCorrecta: 'mi',
    },
    {
      id: 'h-033',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'む',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['to', 'byo', 'na', 'mu'],
      respuestaCorrecta: 'mu',
    },
    {
      id: 'h-034',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'め',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['gya', 'me', 'pi', 'nyu'],
      respuestaCorrecta: 'me',
    },
    {
      id: 'h-035',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'も',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['shi', 'e', 'mo', 'pyo'],
      respuestaCorrecta: 'mo',
    },
    {
      id: 'h-036',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'や',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['pyo', 'ya', 'a', 'ne'],
      respuestaCorrecta: 'ya',
    },
    {
      id: 'h-037',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'ゆ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['gu', 'yu', 'de', 'byu'],
      respuestaCorrecta: 'yu',
    },
    {
      id: 'h-038',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'よ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['sa', 'pi', 'ju', 'yo'],
      respuestaCorrecta: 'yo',
    },
    {
      id: 'h-039',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'ら',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ra', 'e', 'gya', 'ge'],
      respuestaCorrecta: 'ra',
    },
    {
      id: 'h-040',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'り',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['chi', 'do', 'ri', 'be'],
      respuestaCorrecta: 'ri',
    },
    {
      id: 'h-041',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'る',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['hya', 'so', 'yo', 'ru'],
      respuestaCorrecta: 'ru',
    },
    {
      id: 'h-042',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'れ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['e', 'ku', 're', 'da'],
      respuestaCorrecta: 're',
    },
    {
      id: 'h-043',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'ろ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['pi', 'ro', 'pyu', 'cha'],
      respuestaCorrecta: 'ro',
    },
    {
      id: 'h-044',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'わ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ge', 'ro', 'chu', 'wa'],
      respuestaCorrecta: 'wa',
    },
    {
      id: 'h-045',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'を',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['wo', 'gya', 'bya', 'kya'],
      respuestaCorrecta: 'wo',
    },
    {
      id: 'h-046',
      categoria: 'hiragana',
      nivel: 'basico',
      caracter: 'ん',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['n', 'sho', 'pu', 'mo'],
      respuestaCorrecta: 'n',
    },
    {
      id: 'h-047',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'が',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['ga', 'cho', 'fu', 'bi'],
      respuestaCorrecta: 'ga',
    },
    {
      id: 'h-048',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'ぎ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['ro', 'me', 'yu', 'gi'],
      respuestaCorrecta: 'gi',
    },
    {
      id: 'h-049',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'ぐ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['gu', 'su', 'myu', 'hyo'],
      respuestaCorrecta: 'gu',
    },
    {
      id: 'h-050',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'げ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['ge', 'su', 'gu', 'ni'],
      respuestaCorrecta: 'ge',
    },
    {
      id: 'h-051',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'ざ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['re', 'za', 'po', 'mya'],
      respuestaCorrecta: 'za',
    },
    {
      id: 'h-052',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'じ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['be', 'byu', 'ji', 'mi'],
      respuestaCorrecta: 'ji',
    },
    {
      id: 'h-053',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'ず',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['zu', 'mu', 'ji', 'u'],
      respuestaCorrecta: 'zu',
    },
    {
      id: 'h-054',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'ぜ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['ze', 'te', 'ru', 'nyu'],
      respuestaCorrecta: 'ze',
    },
    {
      id: 'h-055',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'だ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['ju', 'go', 'chu', 'da'],
      respuestaCorrecta: 'da',
    },
    {
      id: 'h-056',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'ぢ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['ma', 'ze', 'kyo', 'ji'],
      respuestaCorrecta: 'ji',
    },
    {
      id: 'h-057',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'づ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['pyo', 'mya', 'o', 'zu'],
      respuestaCorrecta: 'zu',
    },
    {
      id: 'h-058',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'で',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['na', 'zu', 'ru', 'de'],
      respuestaCorrecta: 'de',
    },
    {
      id: 'h-059',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'ば',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['ba', 'a', 'ha', 'n'],
      respuestaCorrecta: 'ba',
    },
    {
      id: 'h-060',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'び',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['bi', 'bya', 'be', 'do'],
      respuestaCorrecta: 'bi',
    },
    {
      id: 'h-061',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'ぶ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['hyu', 'ra', 'sha', 'bu'],
      respuestaCorrecta: 'bu',
    },
    {
      id: 'h-062',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'べ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['fu', 'shi', 'be', 'yu'],
      respuestaCorrecta: 'be',
    },
    {
      id: 'h-063',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'ぱ',
      pregunta: '¿Qué sonido representa este carácter con handakuten (゜)?',
      opciones: ['ma', 'ru', 'pa', 'da'],
      respuestaCorrecta: 'pa',
    },
    {
      id: 'h-064',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'ぴ',
      pregunta: '¿Qué sonido representa este carácter con handakuten (゜)?',
      opciones: ['no', 'gi', 'pi', 'ku'],
      respuestaCorrecta: 'pi',
    },
    {
      id: 'h-065',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'ぷ',
      pregunta: '¿Qué sonido representa este carácter con handakuten (゜)?',
      opciones: ['pu', 'ka', 'chu', 'byu'],
      respuestaCorrecta: 'pu',
    },
    {
      id: 'h-066',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'ぺ',
      pregunta: '¿Qué sonido representa este carácter con handakuten (゜)?',
      opciones: ['ro', 'ryo', 'do', 'pe'],
      respuestaCorrecta: 'pe',
    },
    {
      id: 'h-067',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'きゃ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['kya', 'hya', 'na', 'da'],
      respuestaCorrecta: 'kya',
    },
    {
      id: 'h-068',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'きゅ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['ta', 'pya', 'do', 'kyu'],
      respuestaCorrecta: 'kyu',
    },
    {
      id: 'h-069',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'きょ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['fu', 'mu', 'bu', 'kyo'],
      respuestaCorrecta: 'kyo',
    },
    {
      id: 'h-070',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'ぎゃ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['gyo', 'o', 'pu', 'gya'],
      respuestaCorrecta: 'gya',
    },
    {
      id: 'h-071',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'ぎゅ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['gyu', 'ku', 'jo', 'ri'],
      respuestaCorrecta: 'gyu',
    },
    {
      id: 'h-072',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'ぎょ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['gyo', 'shi', 'u', 'to'],
      respuestaCorrecta: 'gyo',
    },
    {
      id: 'h-073',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'しゃ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['sha', 'mi', 'ja', 'bya'],
      respuestaCorrecta: 'sha',
    },
    {
      id: 'h-074',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'しゅ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['bi', 'ta', 'shu', 'he'],
      respuestaCorrecta: 'shu',
    },
    {
      id: 'h-075',
      categoria: 'hiragana',
      nivel: 'avanzado',
      caracter: 'しょ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['cha', 'hyo', 'rya', 'sho'],
      respuestaCorrecta: 'sho',
    },
  ],

  katakana: [
    {
      id: 'k-001',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ア',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ryu', 'a', 'ku', 'pya'],
      respuestaCorrecta: 'a',
    },
    {
      id: 'k-002',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'イ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ju', 'ryo', 'ji', 'i'],
      respuestaCorrecta: 'i',
    },
    {
      id: 'k-003',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ウ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ha', 'za', 'bo', 'u'],
      respuestaCorrecta: 'u',
    },
    {
      id: 'k-004',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'エ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['pyo', 'e', 'ryo', 'cho'],
      respuestaCorrecta: 'e',
    },
    {
      id: 'k-005',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'オ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ba', 'o', 'su', 'ze'],
      respuestaCorrecta: 'o',
    },
    {
      id: 'k-006',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'カ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ka', 'i', 'nyo', 'fu'],
      respuestaCorrecta: 'ka',
    },
    {
      id: 'k-007',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'キ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['sha', 'su', 'za', 'ki'],
      respuestaCorrecta: 'ki',
    },
    {
      id: 'k-008',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ク',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ku', 'kyu', 'po', 'mo'],
      respuestaCorrecta: 'ku',
    },
    {
      id: 'k-009',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ケ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['pyo', 'ba', 'ka', 'ke'],
      respuestaCorrecta: 'ke',
    },
    {
      id: 'k-010',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'コ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ko', 'mi', 'do', 'bi'],
      respuestaCorrecta: 'ko',
    },
    {
      id: 'k-011',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'サ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['i', 'sa', 'zo', 'ma'],
      respuestaCorrecta: 'sa',
    },
    {
      id: 'k-012',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'シ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['shi', 'chi', 'zo', 'sha'],
      respuestaCorrecta: 'shi',
    },
    {
      id: 'k-013',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ス',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ryu', 'fu', 'bu', 'su'],
      respuestaCorrecta: 'su',
    },
    {
      id: 'k-014',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'セ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['no', 'se', 'na', 'sha'],
      respuestaCorrecta: 'se',
    },
    {
      id: 'k-015',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ソ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['so', 'shu', 'a', 'ri'],
      respuestaCorrecta: 'so',
    },
    {
      id: 'k-016',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'タ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['pyu', 'ta', 'wa', 'bu'],
      respuestaCorrecta: 'ta',
    },
    {
      id: 'k-017',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'チ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['n', 'chi', 'na', 'gyu'],
      respuestaCorrecta: 'chi',
    },
    {
      id: 'k-018',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ツ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['su', 'tsu', 'byu', 'cha'],
      respuestaCorrecta: 'tsu',
    },
    {
      id: 'k-019',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'テ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['te', 'ya', 'ta', 'ke'],
      respuestaCorrecta: 'te',
    },
    {
      id: 'k-020',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ト',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ryu', 'to', 'ja', 'u'],
      respuestaCorrecta: 'to',
    },
    {
      id: 'k-021',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ナ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['pi', 'na', 'ne', 'zo'],
      respuestaCorrecta: 'na',
    },
    {
      id: 'k-022',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ニ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['kyu', 'mya', 'ni', 'ne'],
      respuestaCorrecta: 'ni',
    },
    {
      id: 'k-023',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ヌ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ra', 'da', 'za', 'nu'],
      respuestaCorrecta: 'nu',
    },
    {
      id: 'k-024',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ネ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['to', 'kyu', 'chu', 'ne'],
      respuestaCorrecta: 'ne',
    },
    {
      id: 'k-025',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ノ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['se', 'tsu', 'no', 'ki'],
      respuestaCorrecta: 'no',
    },
    {
      id: 'k-026',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ハ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ha', 'myu', 'nu', 'bi'],
      respuestaCorrecta: 'ha',
    },
    {
      id: 'k-027',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ヒ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ka', 'i', 'ryo', 'hi'],
      respuestaCorrecta: 'hi',
    },
    {
      id: 'k-028',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'フ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['gu', 'fu', 'sa', 'pa'],
      respuestaCorrecta: 'fu',
    },
    {
      id: 'k-029',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ヘ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['he', 'na', 'rya', 'ryo'],
      respuestaCorrecta: 'he',
    },
    {
      id: 'k-030',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ホ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['hi', 'ho', 'ya', 'kyu'],
      respuestaCorrecta: 'ho',
    },
    {
      id: 'k-031',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'マ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ma', 'de', 'hya', 'ya'],
      respuestaCorrecta: 'ma',
    },
    {
      id: 'k-032',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ミ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['mi', 'kya', 'zo', 'wa'],
      respuestaCorrecta: 'mi',
    },
    {
      id: 'k-033',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ム',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['shi', 'ko', 'mu', 'pa'],
      respuestaCorrecta: 'mu',
    },
    {
      id: 'k-034',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'メ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ja', 'ryo', 'me', 'chu'],
      respuestaCorrecta: 'me',
    },
    {
      id: 'k-035',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'モ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['wa', 'hya', 'mo', 'hi'],
      respuestaCorrecta: 'mo',
    },
    {
      id: 'k-036',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ヤ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ya', 'e', 'mo', 'sha'],
      respuestaCorrecta: 'ya',
    },
    {
      id: 'k-037',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ユ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ha', 'yu', 'ne', 'bu'],
      respuestaCorrecta: 'yu',
    },
    {
      id: 'k-038',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ヨ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['yo', 'zu', 'go', 'ha'],
      respuestaCorrecta: 'yo',
    },
    {
      id: 'k-039',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ラ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ho', 'ru', 'da', 'ra'],
      respuestaCorrecta: 'ra',
    },
    {
      id: 'k-040',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'リ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ri', 'byu', 'nya', 'hi'],
      respuestaCorrecta: 'ri',
    },
    {
      id: 'k-041',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ル',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['pu', 'ru', 'so', 'do'],
      respuestaCorrecta: 'ru',
    },
    {
      id: 'k-042',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'レ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['re', 'chi', 'gu', 'gi'],
      respuestaCorrecta: 're',
    },
    {
      id: 'k-043',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ロ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['ro', 'ki', 'pi', 'ze'],
      respuestaCorrecta: 'ro',
    },
    {
      id: 'k-044',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ワ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['gyu', 'chu', 'wa', 'ho'],
      respuestaCorrecta: 'wa',
    },
    {
      id: 'k-045',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ヲ',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['wo', 'zo', 'rya', 'ra'],
      respuestaCorrecta: 'wo',
    },
    {
      id: 'k-046',
      categoria: 'katakana',
      nivel: 'basico',
      caracter: 'ン',
      pregunta: '¿Qué sonido representa este carácter?',
      opciones: ['sa', 'pyu', 'wo', 'n'],
      respuestaCorrecta: 'n',
    },
    {
      id: 'k-047',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ガ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['ga', 'nyu', 'be', 'pi'],
      respuestaCorrecta: 'ga',
    },
    {
      id: 'k-048',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ギ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['ryo', 'byu', 'mya', 'gi'],
      respuestaCorrecta: 'gi',
    },
    {
      id: 'k-049',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'グ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['he', 'ji', 'to', 'gu'],
      respuestaCorrecta: 'gu',
    },
    {
      id: 'k-050',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ゲ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['ji', 'bu', 'gu', 'ge'],
      respuestaCorrecta: 'ge',
    },
    {
      id: 'k-051',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ザ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['za', 'fu', 'bo', 'po'],
      respuestaCorrecta: 'za',
    },
    {
      id: 'k-052',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ジ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['ta', 'ga', 'ji', 'n'],
      respuestaCorrecta: 'ji',
    },
    {
      id: 'k-053',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ズ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['zu', 'fu', 'ga', 'wo'],
      respuestaCorrecta: 'zu',
    },
    {
      id: 'k-054',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ゼ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['e', 'ze', 'u', 'ka'],
      respuestaCorrecta: 'ze',
    },
    {
      id: 'k-055',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ダ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['da', 'hyo', 'o', 'gyo'],
      respuestaCorrecta: 'da',
    },
    {
      id: 'k-056',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ヂ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['zo', 'e', 'gi', 'ji'],
      respuestaCorrecta: 'ji',
    },
    {
      id: 'k-057',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ヅ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['zo', 'pyu', 'do', 'zu'],
      respuestaCorrecta: 'zu',
    },
    {
      id: 'k-058',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'デ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['sha', 'su', 'de', 'na'],
      respuestaCorrecta: 'de',
    },
    {
      id: 'k-059',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'バ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['ba', 'pi', 'yu', 'be'],
      respuestaCorrecta: 'ba',
    },
    {
      id: 'k-060',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ビ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['bu', 'bi', 'hi', 'kyo'],
      respuestaCorrecta: 'bi',
    },
    {
      id: 'k-061',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ブ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['pyu', 'ku', 'bu', 'ru'],
      respuestaCorrecta: 'bu',
    },
    {
      id: 'k-062',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ベ',
      pregunta: '¿Qué sonido representa este carácter con dakuten (゛)?',
      opciones: ['kya', 'pya', 'be', 'ko'],
      respuestaCorrecta: 'be',
    },
    {
      id: 'k-063',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'パ',
      pregunta: '¿Qué sonido representa este carácter con handakuten (゜)?',
      opciones: ['na', 'pa', 'hyu', 'ho'],
      respuestaCorrecta: 'pa',
    },
    {
      id: 'k-064',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ピ',
      pregunta: '¿Qué sonido representa este carácter con handakuten (゜)?',
      opciones: ['pi', 'zu', 'yu', 're'],
      respuestaCorrecta: 'pi',
    },
    {
      id: 'k-065',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'プ',
      pregunta: '¿Qué sonido representa este carácter con handakuten (゜)?',
      opciones: ['nyu', 'pu', 'no', 'ga'],
      respuestaCorrecta: 'pu',
    },
    {
      id: 'k-066',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ペ',
      pregunta: '¿Qué sonido representa este carácter con handakuten (゜)?',
      opciones: ['a', 'pe', 'ra', 'sha'],
      respuestaCorrecta: 'pe',
    },
    {
      id: 'k-067',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'キャ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['mya', 'ho', 'kyo', 'kya'],
      respuestaCorrecta: 'kya',
    },
    {
      id: 'k-068',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'キュ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['kyu', 'se', 'ra', 'gu'],
      respuestaCorrecta: 'kyu',
    },
    {
      id: 'k-069',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'キョ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['ba', 'shu', 'kyo', 'se'],
      respuestaCorrecta: 'kyo',
    },
    {
      id: 'k-070',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ギャ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['i', 'gya', 'to', 'cho'],
      respuestaCorrecta: 'gya',
    },
    {
      id: 'k-071',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ギュ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['ba', 'de', 'gyu', 'yu'],
      respuestaCorrecta: 'gyu',
    },
    {
      id: 'k-072',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ギョ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['kyu', 'gyo', 'zu', 'ba'],
      respuestaCorrecta: 'gyo',
    },
    {
      id: 'k-073',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'シャ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['bya', 'mya', 'sha', 'nyu'],
      respuestaCorrecta: 'sha',
    },
    {
      id: 'k-074',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'シュ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['shu', 'bo', 'zu', 'ru'],
      respuestaCorrecta: 'shu',
    },
    {
      id: 'k-075',
      categoria: 'katakana',
      nivel: 'avanzado',
      caracter: 'ショ',
      pregunta: '¿Qué sonido representa esta combinación?',
      opciones: ['pi', 'gya', 'hyu', 'sho'],
      respuestaCorrecta: 'sho',
    },
  ],

  kanji: [
    {
      id: 'kj-001',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '一',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: uno)',
      opciones: ['ichi', 'tsuki', 'kou', 'ko'],
      respuestaCorrecta: 'ichi',
    },
    {
      id: 'kj-002',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '二',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: dos)',
      opciones: ['ie', 'kuruma', 'hachi', 'ni'],
      respuestaCorrecta: 'ni',
    },
    {
      id: 'kj-003',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '三',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: tres)',
      opciones: ['ni', 'san', 'yon', 'go'],
      respuestaCorrecta: 'san',
    },
    {
      id: 'kj-004',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '四',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: cuatro)',
      opciones: ['hito', 'hachi', 'kuni', 'yon'],
      respuestaCorrecta: 'yon',
    },
    {
      id: 'kj-005',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '五',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: cinco)',
      opciones: ['go', 'gaku', 'kai', 'en'],
      respuestaCorrecta: 'go',
    },
    {
      id: 'kj-006',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '六',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: seis)',
      opciones: ['roku', 'hanashi', 'ichi', 'kane'],
      respuestaCorrecta: 'roku',
    },
    {
      id: 'kj-007',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '七',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: siete)',
      opciones: ['kuruma', 'haha', 'chichi', 'nana'],
      respuestaCorrecta: 'nana',
    },
    {
      id: 'kj-008',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '八',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: ocho)',
      opciones: ['hachi', 'gaku', 'mizu', 'hon'],
      respuestaCorrecta: 'hachi',
    },
    {
      id: 'kj-009',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '九',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: nueve)',
      opciones: ['ie', 'mizu', 'fu', 'kyuu'],
      respuestaCorrecta: 'kyuu',
    },
    {
      id: 'kj-010',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '十',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: diez)',
      opciones: ['haha', 'go', 'juu', 'ni'],
      respuestaCorrecta: 'juu',
    },
    {
      id: 'kj-011',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '百',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: cien)',
      opciones: ['sen', 'san', 'hyaku', 'mizu'],
      respuestaCorrecta: 'hyaku',
    },
    {
      id: 'kj-012',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '千',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: mil)',
      opciones: ['tsuki', 'sen', 'onna', 'nomu'],
      respuestaCorrecta: 'sen',
    },
    {
      id: 'kj-013',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '円',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: yen)',
      opciones: ['go', 'en', 'yon', 'roku'],
      respuestaCorrecta: 'en',
    },
    {
      id: 'kj-014',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '年',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: año)',
      opciones: ['eki', 'den', 'fun', 'nen'],
      respuestaCorrecta: 'nen',
    },
    {
      id: 'kj-015',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '月',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: mes)',
      opciones: ['tsu', 'ki', 'mise', 'tsuki'],
      respuestaCorrecta: 'tsuki',
    },
    {
      id: 'kj-016',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '日',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: día)',
      opciones: ['ni', 'chi', 'sei', 'hi'],
      respuestaCorrecta: 'hi',
    },
    {
      id: 'kj-017',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '時',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: hora)',
      opciones: ['toki', 'saki', 'ki', 'haha'],
      respuestaCorrecta: 'toki',
    },
    {
      id: 'kj-018',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '分',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: minuto)',
      opciones: ['yomu', 'ichi', 'fun', 'nen'],
      respuestaCorrecta: 'fun',
    },
    {
      id: 'kj-019',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '人',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: persona)',
      opciones: ['haha', 'tsu', 'hito', 'gaku'],
      respuestaCorrecta: 'hito',
    },
    {
      id: 'kj-020',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '男',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: hombre)',
      opciones: ['hon', 'otoko', 'mi', 'hachi'],
      respuestaCorrecta: 'otoko',
    },
    {
      id: 'kj-021',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '女',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: mujer)',
      opciones: ['saki', 'onna', 'ki', 'kyuu'],
      respuestaCorrecta: 'onna',
    },
    {
      id: 'kj-022',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '子',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: niño)',
      opciones: ['saki', 'ko', 'fun', 'mi'],
      respuestaCorrecta: 'ko',
    },
    {
      id: 'kj-023',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '父',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: padre)',
      opciones: ['ki', 'chichi', 'yomu', 'mizu'],
      respuestaCorrecta: 'chichi',
    },
    {
      id: 'kj-024',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '母',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: madre)',
      opciones: ['ko', 'hito', 'chichi', 'haha'],
      respuestaCorrecta: 'haha',
    },
    {
      id: 'kj-025',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '友',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: amigo)',
      opciones: ['tomo', 'yon', 'tsuki', 'hachi'],
      respuestaCorrecta: 'tomo',
    },
    {
      id: 'kj-026',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '先',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: anterior)',
      opciones: ['sei', 'roku', 'mi', 'saki'],
      respuestaCorrecta: 'saki',
    },
    {
      id: 'kj-027',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '生',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: vida)',
      opciones: ['sei', 'kyuu', 'otoko', 'ko'],
      respuestaCorrecta: 'sei',
    },
    {
      id: 'kj-028',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '学',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: estudio)',
      opciones: ['yomu', 'mise', 'gaku', 'shi'],
      respuestaCorrecta: 'gaku',
    },
    {
      id: 'kj-029',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '校',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: escuela)',
      opciones: ['ie', 'kou', 'iu', 'mise'],
      respuestaCorrecta: 'kou',
    },
    {
      id: 'kj-030',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '食',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: comida)',
      opciones: ['ko', 'shoku', 'gaku', 'hito'],
      respuestaCorrecta: 'shoku',
    },
    {
      id: 'kj-031',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '飲',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: beber)',
      opciones: ['sei', 'go', 'nomu', 'ko'],
      respuestaCorrecta: 'nomu',
    },
    {
      id: 'kj-032',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '見',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: ver)',
      opciones: ['mi', 'hanashi', 'ni', 'mise'],
      respuestaCorrecta: 'mi',
    },
    {
      id: 'kj-033',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '聞',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: oír)',
      opciones: ['ki', 'ie', 'kuruma', 'tsu'],
      respuestaCorrecta: 'ki',
    },
    {
      id: 'kj-034',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '言',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: decir)',
      opciones: ['iu', 'ki', 'kaku', 'kai'],
      respuestaCorrecta: 'iu',
    },
    {
      id: 'kj-035',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '読',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: leer)',
      opciones: ['san', 'iu', 'yomu', 'ichi'],
      respuestaCorrecta: 'yomu',
    },
    {
      id: 'kj-036',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '書',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: escribir)',
      opciones: ['kaku', 'toki', 'kai', 'iu'],
      respuestaCorrecta: 'kaku',
    },
    {
      id: 'kj-037',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '話',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: conversación)',
      opciones: ['tsu', 'chichi', 'yomu', 'hanashi'],
      respuestaCorrecta: 'hanashi',
    },
    {
      id: 'kj-038',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '買',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: comprar)',
      opciones: ['kaku', 'hanashi', 'kai', 'tsu'],
      respuestaCorrecta: 'kai',
    },
    {
      id: 'kj-039',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '金',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: dinero)',
      opciones: ['kane', 'otoko', 'nana', 'chi'],
      respuestaCorrecta: 'kane',
    },
    {
      id: 'kj-040',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '車',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: coche)',
      opciones: ['mizu', 'kuruma', 'kai', 'hon'],
      respuestaCorrecta: 'kuruma',
    },
    {
      id: 'kj-041',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '電',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: electricidad)',
      opciones: ['hyaku', 'en', 'eki', 'den'],
      respuestaCorrecta: 'den',
    },
    {
      id: 'kj-042',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '駅',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: estación)',
      opciones: ['juu', 'yomu', 'eki', 'ichi'],
      respuestaCorrecta: 'eki',
    },
    {
      id: 'kj-043',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '道',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: camino)',
      opciones: ['shi', 'kai', 'kyuu', 'michi'],
      respuestaCorrecta: 'michi',
    },
    {
      id: 'kj-044',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '店',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: tienda)',
      opciones: ['hyaku', 'san', 'sen', 'mise'],
      respuestaCorrecta: 'mise',
    },
    {
      id: 'kj-045',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '家',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: casa)',
      opciones: ['ie', 'juu', 'ki', 'den'],
      respuestaCorrecta: 'ie',
    },
    {
      id: 'kj-046',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '国',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: país)',
      opciones: ['ni', 'san', 'mise', 'kuni'],
      respuestaCorrecta: 'kuni',
    },
    {
      id: 'kj-047',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '語',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: idioma)',
      opciones: ['ni', 'otoko', 'iu', 'go'],
      respuestaCorrecta: 'go',
    },
    {
      id: 'kj-048',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '本',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: libro)',
      opciones: ['otoko', 'ni', 'hon', 'tsuki'],
      respuestaCorrecta: 'hon',
    },
    {
      id: 'kj-049',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '水',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: agua)',
      opciones: ['mizu', 'kuruma', 'hyaku', 'kuni'],
      respuestaCorrecta: 'mizu',
    },
    {
      id: 'kj-050',
      categoria: 'kanji',
      nivel: 'avanzado',
      caracter: '火',
      pregunta: '¿Cuál es la lectura de este kanji? (significado: fuego)',
      opciones: ['eki', 'ko', 'hi', 'onna'],
      respuestaCorrecta: 'hi',
    },
  ],
};

NihonCheck.obtenerTodasLasPreguntas = function () {
  return [
    ...NihonCheck.PREGUNTAS.hiragana,
    ...NihonCheck.PREGUNTAS.katakana,
    ...NihonCheck.PREGUNTAS.kanji,
  ];
};

window.NihonCheck = NihonCheck;
